---

- name: ensure lm-sensors is installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - lm-sensors
  become: true

- name: copy fancontrol script
  template:
    src: fan-control
    dest: /usr/local/bin/fancontrol
    owner: root
    group: root
    mode: '755'

- name: setup cron for fancontrol
  cron:
    name: "check temps"
    minute: "*"
    job: "fancontrol"